# -*- coding: utf-8 -*-
"""aiolearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXd0FnoiCm_dZRk5nGTQOY6P1Q5-QuIU
"""

import matplotlib.pyplot as plt
import cv2

image = cv2.imread('Untitled.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

model = cv2.CascadeClassifier('model.xml')
face = model.detectMultiScale(image)

x = face[0][0]
y = face[0][1]
a = face[0][2]
b = face[0][3]

image = cv2.rectangle(image, (x, y), (x+a, y+b), (255,0,0), 3)

plt.imshow(image)

